### ISSUE TITLE
Difference between "http" and "https" version of the api

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [alex9smith/gdelt-doc-api#3]
If you change "https://api.gdeltproject.org/api/v2/doc/doc?query={query_string}&mode={mode}&format=json" with "http://api.gdeltproject.org/api/v2/doc/doc?query={query_string}&mode={mode}&format=json" (_notice http and https_) in _query method, the code still works. Just wondering what's the difference?

**Comment by alex9smith** [comment]
The GDELT API endpoint responds to requests over both HTTP and HTTPS. This library will always use HTTPS so data's encrypted between the client and server, but the response from the API is identical so the library will still work. I wouldn't recommend that though.

If you've got any security concerns about the API responding on HTTP then you'd need to contact GDELT directly. This project's not affiliated with them in any way.
